// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "./include/wakelock_plus/messages.g.h"

#if TARGET_OS_OSX
@import FlutterMacOS;
#else
@import Flutter;
#endif

static BOOL __attribute__((unused)) FLTPigeonDeepEquals(id _Nullable a, id _Nullable b) {
  if (a == b) {
    return YES;
  }
  if (a == nil) {
    return b == [NSNull null];
  }
  if (b == nil) {
    return a == [NSNull null];
  }
  if ([a isKindOfClass:[NSNumber class]] && [b isKindOfClass:[NSNumber class]]) {
    return [a isEqual:b] || (isnan([(NSNumber *)a doubleValue]) && isnan([(NSNumber *)b doubleValue]));
  }
  if ([a isKindOfClass:[NSArray class]] && [b isKindOfClass:[NSArray class]]) {
    NSArray *arrayA = (NSArray *)a;
    NSArray *arrayB = (NSArray *)b;
    if (arrayA.count != arrayB.count) {
      return NO;
    }
    for (NSUInteger i = 0; i < arrayA.count; i++) {
      if (!FLTPigeonDeepEquals(arrayA[i], arrayB[i])) {
        return NO;
      }
    }
    return YES;
  }
  if ([a isKindOfClass:[NSDictionary class]] && [b isKindOfClass:[NSDictionary class]]) {
    NSDictionary *dictA = (NSDictionary *)a;
    NSDictionary *dictB = (NSDictionary *)b;
    if (dictA.count != dictB.count) {
      return NO;
    }
    for (id keyA in dictA) {
      id valueA = dictA[keyA];
      BOOL found = NO;
      for (id keyB in dictB) {
        if (FLTPigeonDeepEquals(keyA, keyB)) {
          id valueB = dictB[keyB];
          if (FLTPigeonDeepEquals(valueA, valueB)) {
            found = YES;
            break;
          } else {
            return NO;
          }
        }
      }
      if (!found) {
        return NO;
      }
    }
    return YES;
  }
  return [a isEqual:b];
}

static NSUInteger __attribute__((unused)) FLTPigeonDeepHash(id _Nullable value) {
  if (value == nil || value == (id)[NSNull null]) {
    return 0;
  }
  if ([value isKindOfClass:[NSNumber class]]) {
    NSNumber *n = (NSNumber *)value;
    double d = n.doubleValue;
    if (isnan(d)) {
      // Normalize NaN to a consistent hash.
      return (NSUInteger)0x7FF8000000000000;
    }
    if (d == 0.0) {
      // Normalize -0.0 to 0.0 so they have the same hash code.
      d = 0.0;
    }
    return @(d).hash;
  }
  if ([value isKindOfClass:[NSArray class]]) {
    NSUInteger result = 1;
    for (id item in (NSArray *)value) {
      result = result * 31 + FLTPigeonDeepHash(item);
    }
    return result;
  }
  if ([value isKindOfClass:[NSDictionary class]]) {
    NSUInteger result = 0;
    NSDictionary *dict = (NSDictionary *)value;
    for (id key in dict) {
      result += ((FLTPigeonDeepHash(key) * 31) ^ FLTPigeonDeepHash(dict[key]));
    }
    return result;
  }
  return [value hash];
}

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface WAKELOCKPLUSToggleMessage ()
+ (WAKELOCKPLUSToggleMessage *)fromList:(NSArray<id> *)list;
+ (nullable WAKELOCKPLUSToggleMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface WAKELOCKPLUSIsEnabledMessage ()
+ (WAKELOCKPLUSIsEnabledMessage *)fromList:(NSArray<id> *)list;
+ (nullable WAKELOCKPLUSIsEnabledMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation WAKELOCKPLUSToggleMessage
+ (instancetype)makeWithEnable:(nullable NSNumber *)enable {
  WAKELOCKPLUSToggleMessage* pigeonResult = [[WAKELOCKPLUSToggleMessage alloc] init];
  pigeonResult.enable = enable;
  return pigeonResult;
}
+ (WAKELOCKPLUSToggleMessage *)fromList:(NSArray<id> *)list {
  WAKELOCKPLUSToggleMessage *pigeonResult = [[WAKELOCKPLUSToggleMessage alloc] init];
  pigeonResult.enable = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable WAKELOCKPLUSToggleMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [WAKELOCKPLUSToggleMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.enable ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  WAKELOCKPLUSToggleMessage *other = (WAKELOCKPLUSToggleMessage *)object;
  return FLTPigeonDeepEquals(self.enable, other.enable);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.enable);
  return result;
}
@end

@implementation WAKELOCKPLUSIsEnabledMessage
+ (instancetype)makeWithEnabled:(nullable NSNumber *)enabled {
  WAKELOCKPLUSIsEnabledMessage* pigeonResult = [[WAKELOCKPLUSIsEnabledMessage alloc] init];
  pigeonResult.enabled = enabled;
  return pigeonResult;
}
+ (WAKELOCKPLUSIsEnabledMessage *)fromList:(NSArray<id> *)list {
  WAKELOCKPLUSIsEnabledMessage *pigeonResult = [[WAKELOCKPLUSIsEnabledMessage alloc] init];
  pigeonResult.enabled = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable WAKELOCKPLUSIsEnabledMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [WAKELOCKPLUSIsEnabledMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.enabled ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  WAKELOCKPLUSIsEnabledMessage *other = (WAKELOCKPLUSIsEnabledMessage *)object;
  return FLTPigeonDeepEquals(self.enabled, other.enabled);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.enabled);
  return result;
}
@end

@interface WAKELOCKPLUSMessagesPigeonCodecReader : FlutterStandardReader
@end
@implementation WAKELOCKPLUSMessagesPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [WAKELOCKPLUSToggleMessage fromList:[self readValue]];
    case 130: 
      return [WAKELOCKPLUSIsEnabledMessage fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface WAKELOCKPLUSMessagesPigeonCodecWriter : FlutterStandardWriter
@end
@implementation WAKELOCKPLUSMessagesPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[WAKELOCKPLUSToggleMessage class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[WAKELOCKPLUSIsEnabledMessage class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface WAKELOCKPLUSMessagesPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation WAKELOCKPLUSMessagesPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[WAKELOCKPLUSMessagesPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[WAKELOCKPLUSMessagesPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *WAKELOCKPLUSGetMessagesCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    WAKELOCKPLUSMessagesPigeonCodecReaderWriter *readerWriter = [[WAKELOCKPLUSMessagesPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpWAKELOCKPLUSWakelockPlusApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WAKELOCKPLUSWakelockPlusApi> *api) {
  SetUpWAKELOCKPLUSWakelockPlusApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpWAKELOCKPLUSWakelockPlusApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WAKELOCKPLUSWakelockPlusApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.wakelock_plus_platform_interface.WakelockPlusApi.toggle", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WAKELOCKPLUSGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(toggleMsg:error:)], @"WAKELOCKPLUSWakelockPlusApi api (%@) doesn't respond to @selector(toggleMsg:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        WAKELOCKPLUSToggleMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api toggleMsg:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.wakelock_plus_platform_interface.WakelockPlusApi.isEnabled", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WAKELOCKPLUSGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isEnabledWithError:)], @"WAKELOCKPLUSWakelockPlusApi api (%@) doesn't respond to @selector(isEnabledWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        WAKELOCKPLUSIsEnabledMessage *output = [api isEnabledWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
