// Autogenerated from Pigeon (v26.0.1), enhanced, bug-fixed and UI-ready single file.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/material.dart';
import 'package:wakelock_plus_platform_interface/messages.g.dart';

/// Custom codec supporting advanced Pigeon object serialization.
class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is ToggleMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is IsEnabledMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return ToggleMessage.decode(readValue(buffer)!);
      case 130:
        return IsEnabledMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Extended Test API providing diagnostics, automation, and performance benchmarking.
///
/// NOTE: This class is intended for test and simulation use (uses
/// TestDefaultBinaryMessengerBinding when setUp is called). It adds a few
/// convenient helper methods that wrap the core generated Pigeon methods.
abstract class TestWakelockPlusApi {
  static TestDefaultBinaryMessengerBinding? get _testBinding => TestDefaultBinaryMessengerBinding.instance;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Core functions (provided by concrete test implementation)
  void toggle(ToggleMessage msg);

  IsEnabledMessage isEnabled();

  // -------------------------
  // Helper / Extended Methods
  // -------------------------

  /// Async wrapper to query enabled state safely.
  Future<bool> isEnabledAsync() async {
    try {
      final IsEnabledMessage msg = isEnabled();
      return msg.enabled ?? false;
    } catch (e) {
      // If the test implementation throws, treat as disabled and log.
      logState('isEnabledAsync error: \$e');
      return false;
    }
  }

  /// Enables wakelock for a specific duration.
  Future<void> enableFor(Duration duration) async {
    toggle(ToggleMessage()..enable = true);
    await Future.delayed(duration);
    toggle(ToggleMessage()..enable = false);
  }

  /// Runs a callback while wakelock remains enabled.
  Future<void> runWithWakelock(Future<void> Function() callback) async {
    toggle(ToggleMessage()..enable = true);
    try {
      await callback();
    } finally {
      toggle(ToggleMessage()..enable = false);
    }
  }

  /// Collects runtime diagnostic data.
  Future<Map<String, dynamic>> diagnostics() async {
    final bool enabledState = await isEnabledAsync();
    return {
      'enabled': enabledState,
      'timestamp': DateTime.now().toIso8601String(),
      'environment': 'Flutter Test',
      'apiVersion': '2.0.0-extended',
    };
  }

  /// Measures toggle execution performance (approximate).
  Future<Duration> measurePerformance() async {
    final start = DateTime.now();
    toggle(ToggleMessage()..enable = true);
    toggle(ToggleMessage()..enable = false);
    return DateTime.now().difference(start);
  }

  /// Sets up the test message channels. If [api] is null the mock handlers are removed.
  static void setUp(TestWakelockPlusApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    final toggleChannel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.wakelock_plus_platform_interface.WakelockPlusApi.toggle$messageChannelSuffix',
      pigeonChannelCodec,
      binaryMessenger: binaryMessenger,
    );
    final enabledChannel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.wakelock_plus_platform_interface.WakelockPlusApi.isEnabled$messageChannelSuffix',
      pigeonChannelCodec,
      binaryMessenger: binaryMessenger,
    );

    if (_testBinding == null) {
      throw StateError('TestDefaultBinaryMessengerBinding is not initialized. Call TestWidgetsFlutterBinding.ensureInitialized() in tests.');
    }

    if (api == null) {
      _testBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(toggleChannel, null);
      _testBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(enabledChannel, null);
    } else {
      _testBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(toggleChannel, (Object? message) async {
        final List<Object?> args = (message as List<Object?>?)!;
        final ToggleMessage? arg = args[0] as ToggleMessage?;
        if (arg == null) return wrapResponse(error: PlatformException(code: 'null-arg', message: 'ToggleMessage was null'));
        try {
          api.toggle(arg);
          return wrapResponse(empty: true);
        } on PlatformException catch (e) {
          return wrapResponse(error: e);
        } catch (e) {
          return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
        }
      });

      _testBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(enabledChannel, (Object? message) async {
        try {
          final IsEnabledMessage output = api.isEnabled();
          return <Object?>[output];
        } on PlatformException catch (e) {
          return wrapResponse(error: e);
        } catch (e) {
          return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
        }
      });
    }
  }

  /// Stress test with configurable cycles.
  Future<void> stressTest({int cycles = 5, Duration delay = const Duration(milliseconds: 500)}) async {
    for (int i = 0; i < cycles; i++) {
      toggle(ToggleMessage()..enable = true);
      await Future.delayed(delay);
      toggle(ToggleMessage()..enable = false);
    }
  }

  /// Stream monitoring of wakelock state (async-aware).
  Stream<bool> monitorState({Duration interval = const Duration(seconds: 2)}) async* {
    while (true) {
      final bool state = await isEnabledAsync();
      yield state;
      await Future.delayed(interval);
    }
  }

  /// Export current diagnostics as a formatted string.
  Future<String> exportDiagnostics() async {
    final data = await diagnostics();
    return data.entries.map((e) => '${e.key}: ${e.value}').join('\n');
  }

  /// Logs state with formatted timestamp.
  void logState(String message) {
    // Use debugPrint when available to avoid test flakiness.
    debugPrint('[WakelockPlusTest] ${DateTime.now().toIso8601String()} — $message');
  }

  /// Watchdog that keeps wakelock enabled.
  Future<void> watchdog({Duration checkInterval = const Duration(seconds: 10)}) async {
    while (true) {
      final bool state = await isEnabledAsync();
      if (!state) {
        logState('⚙️ Re-enabling wakelock after unexpected disable.');
        toggle(ToggleMessage()..enable = true);
      }
      await Future.delayed(checkInterval);
    }
  }

  /// Tracks test benchmark metrics.
  Future<Map<String, dynamic>> benchmark({int iterations = 10}) async {
    final start = DateTime.now();
    for (int i = 0; i < iterations; i++) {
      toggle(ToggleMessage()..enable = true);
      toggle(ToggleMessage()..enable = false);
    }
    final elapsed = DateTime.now().difference(start);
    return {
      'iterations': iterations,
      'totalTimeMs': elapsed.inMilliseconds,
      'avgPerToggleMs': elapsed.inMilliseconds / (iterations * 2),
    };
  }

  /// Simulates different platform behaviors for test flexibility.
  Future<void> simulatePlatformBehavior(String platform) async {
    logState('Simulating behavior for platform: $platform');
    await Future.delayed(const Duration(seconds: 1));
    toggle(ToggleMessage()..enable = platform.toLowerCase().contains('android'));
  }

  /// Graceful shutdown utility.
  Future<void> gracefulShutdown() async {
    logState('Initiating wakelock shutdown...');
    toggle(ToggleMessage()..enable = false);
  }
}

// -------------------------
// Small diagnostic UI widget
// -------------------------
// This widget can be used in debug apps or test harnesses to interactively
// inspect and control a TestWakelockPlusApi instance. It is intentionally
// lightweight and visually appealing (rounded card, soft shadows, clear labels).

class WakelockTestPanel extends StatefulWidget {
  final TestWakelockPlusApi api;
  const WakelockTestPanel({Key? key, required this.api}) : super(key: key);

  @override
  State<WakelockTestPanel> createState() => _WakelockTestPanelState();
}

class _WakelockTestPanelState extends State<WakelockTestPanel> {
  bool _enabled = false;
  bool _loading = true;
  Timer? _pollTimer;

  @override
  void initState() {
    super.initState();
    _refresh();
    _pollTimer = Timer.periodic(const Duration(seconds: 2), (_) => _refresh());
  }

  @override
  void dispose() {
    _pollTimer?.cancel();
    super.dispose();
  }

  Future<void> _refresh() async {
    setState(() => _loading = true);
    try {
      final v = await widget.api.isEnabledAsync();
      if (mounted) setState(() => _enabled = v);
    } catch (e) {
      widget.api.logState('UI refresh error: \$e');
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  Future<void> _toggle() async {
    setState(() => _loading = true);
    try {
      widget.api.toggle(ToggleMessage()..enable = !_enabled);
      // brief delay for state to settle in test harness
      await Future.delayed(const Duration(milliseconds: 150));
      await _refresh();
    } catch (e) {
      widget.api.logState('UI toggle error: \$e');
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 8,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(12.0),
        child: Column(mainAxisSize: MainAxisSize.min, children: [
          Row(children: [
            Expanded(
              child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                Text('Wakelock Test Panel', style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold)),
                const SizedBox(height: 4),
                Text(_loading ? 'Loading...' : (_enabled ? 'Enabled — device kept awake' : 'Disabled — normal sleep allowed'), style: Theme.of(context).textTheme.bodySmall),
              ]),
            ),
            _buildStatusCircle()
          ]),
          const SizedBox(height: 12),
          Row(children: [
            Expanded(
              child: ElevatedButton(
                onPressed: _loading ? null : _toggle,
                style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 12), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10))),
                child: _loading
                    ? const SizedBox(width: 18, height: 18, child: CircularProgressIndicator(strokeWidth: 2))
                    : Text(_enabled ? 'Disable' : 'Enable', style: const TextStyle(fontWeight: FontWeight.w600)),
              ),
            ),
            const SizedBox(width: 8),
            IconButton(
              tooltip: 'Diagnostics',
              onPressed: () async {
                final diag = await widget.api.diagnostics();
                if (!mounted) return;
                showDialog<void>(
                  context: context,
                  builder: (context) => AlertDialog(
                    title: const Text('Diagnostics'),
                    content: SingleChildScrollView(child: Text(diag.entries.map((e) => '${e.key}: ${e.value}').join('\n'))),
                    actions: [TextButton(onPressed: () => Navigator.of(context).pop(), child: const Text('Close'))],
                  ),
                );
              },
              icon: Icon(Icons.info_outline, color: Theme.of(context).colorScheme.primary),
            )
          ])
        ]),
      ),
    );
  }

  Widget _buildStatusCircle() {
    return AnimatedContainer(
      duration: const Duration(milliseconds: 300),
      width: 46,
      height: 46,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        gradient: _enabled ? const LinearGradient(colors: [Color(0xFF00C9A7), Color(0xFF92FE9D)]) : const LinearGradient(colors: [Color(0xFFF1F5F9), Color(0xFFF8FAFC)]),
        boxShadow: _enabled ? [BoxShadow(color: Colors.black.withOpacity(0.12), blurRadius: 8, offset: const Offset(0, 4))] : null,
      ),
      child: Center(
        child: _loading
            ? const SizedBox(width: 18, height: 18, child: CircularProgressIndicator(strokeWidth: 2))
            : Icon(_enabled ? Icons.visibility : Icons.visibility_off, color: _enabled ? Colors.white : Colors.grey[700]),
      ),
    );
  }
}

// End of file: Wakelock Plus Full (test + UI helpers)
 
