// Autogenerated from Pigeon (v26.0.1) — enhanced and bug-fixed single-file API
// Do not edit the Pigeon-generated portions when re-generating from .pigeon files.
// This file has been manually extended with additional utilities and diagnostics.

// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:collection';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer, debugPrint;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "\$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) return <Object?>[];
  if (error == null) return <Object?>[result];
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) return true;
  if (a is List && b is List) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (!_deepEquals(a[i], b[i])) return false;
    }
    return true;
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) return false;
    for (final key in a.keys) {
      if (!b.containsKey(key)) return false;
      if (!_deepEquals(a[key], b[key])) return false;
    }
    return true;
  }
  return a == b;
}

/// Message for toggling the wakelock on the platform side.
class ToggleMessage {
  ToggleMessage({this.enable});

  bool? enable;

  List<Object?> _toList() => <Object?>[enable];
  Object encode() => _toList();

  static ToggleMessage decode(Object result) {
    result as List<Object?>;
    return ToggleMessage(enable: result[0] as bool?);
  }

  @override
  bool operator ==(Object other) {
    if (other is! ToggleMessage || other.runtimeType != runtimeType) return false;
    if (identical(this, other)) return true;
    return _deepEquals(encode(), other.encode());
  }

  @override
  int get hashCode => Object.hashAll(_toList());
}

/// Message for reporting the wakelock state from the platform side.
class IsEnabledMessage {
  IsEnabledMessage({this.enabled});

  bool? enabled;

  List<Object?> _toList() => <Object?>[enabled];
  Object encode() => _toList();

  static IsEnabledMessage decode(Object result) {
    result as List<Object?>;
    return IsEnabledMessage(enabled: result[0] as bool?);
  }

  @override
  bool operator ==(Object other) {
    if (other is! IsEnabledMessage || other.runtimeType != runtimeType) return false;
    if (identical(this, other)) return true;
    return _deepEquals(encode(), other.encode());
  }

  @override
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ToggleMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is IsEnabledMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return ToggleMessage.decode(readValue(buffer)!);
      case 130:
        return IsEnabledMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class WakelockPlusApi {
  /// Constructor for [WakelockPlusApi]. If [binaryMessenger] is null, the
  /// default BinaryMessenger will be used which routes to the host platform.
  WakelockPlusApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();
  final String pigeonVar_messageChannelSuffix;

  /// Sends a toggle request to the host platform.
  Future<void> toggle(ToggleMessage msg) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.wakelock_plus_platform_interface.WakelockPlusApi.toggle\$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );

    final Object? rawReply = await pigeonVar_channel.send(<Object?>[msg]);
    final List<Object?>? pigeonVar_replyList = rawReply as List<Object?>?;

    if (pigeonVar_replyList == null) throw _createConnectionError(pigeonVar_channelName);
    if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    }
    return;
  }

  /// Queries the platform whether wakelock is enabled.
  Future<IsEnabledMessage> isEnabled() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.wakelock_plus_platform_interface.WakelockPlusApi.isEnabled\$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );

    final Object? rawReply = await pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList = rawReply as List<Object?>?;

    if (pigeonVar_replyList == null) throw _createConnectionError(pigeonVar_channelName);
    if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    }
    if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    }
    return (pigeonVar_replyList[0] as IsEnabledMessage?)!;
  }

  // =====================
  // Additional utility functions (bug-fixed and robust)
  // =====================

  /// Enable wakelock for exactly [duration], then release it.
  Future<void> enableFor(Duration duration) async {
    await toggle(ToggleMessage(enable: true));
    await Future.delayed(duration);
    await toggle(ToggleMessage(enable: false));
  }

  /// Toggle and return the updated state from the platform.
  Future<bool> toggleAndGet() async {
    final IsEnabledMessage current = await isEnabled();
    final bool newState = !(current.enabled ?? false);
    await toggle(ToggleMessage(enable: newState));
    return newState;
  }

  /// Polls the wake-lock state periodically and emits it as a stream.
  Stream<bool> watchState({Duration interval = const Duration(seconds: 5)}) async* {
    while (true) {
      final IsEnabledMessage s = await isEnabled();
      yield s.enabled ?? false;
      await Future.delayed(interval);
    }
  }

  /// Return a diagnostics snapshot useful for logging or debugging.
  Future<Map<String, Object?>> snapshot() async {
    final IsEnabledMessage s = await isEnabled();
    return <String, Object?>{
      'enabled': s.enabled,
      'channelSuffix': pigeonVar_messageChannelSuffix,
      'messengerProvided': pigeonVar_binaryMessenger != null,
      'timestamp': DateTime.now().toIso8601String(),
    };
  }

  /// Keep wakelock in the desired [state] until [condition] returns false.
  /// This is a safe loop that checks the condition periodically.
  Future<void> maintainWhile(Future<bool> Function() condition, {Duration checkInterval = const Duration(seconds: 5)}) async {
    final bool shouldStart = await condition();
    await toggle(ToggleMessage(enable: shouldStart));
    while (await condition()) {
      await Future.delayed(checkInterval);
    }
    await toggle(ToggleMessage(enable: false));
  }

  /// Schedules an on/off cycle at future times.
  Future<void> schedule({required DateTime startAt, required Duration duration}) async {
    final Duration untilStart = startAt.difference(DateTime.now());
    if (untilStart > Duration.zero) await Future.delayed(untilStart);
    await toggle(ToggleMessage(enable: true));
    await Future.delayed(duration);
    await toggle(ToggleMessage(enable: false));
  }

  /// Run a simple benchmark of toggling performance.
  Future<Map<String, Object?>> benchmark(int cycles) async {
    if (cycles <= 0) throw ArgumentError.value(cycles, 'cycles', 'must be > 0');
    final Stopwatch sw = Stopwatch()..start();
    for (var i = 0; i < cycles; i++) {
      await toggle(ToggleMessage(enable: i % 2 == 0));
    }
    sw.stop();
    return <String, Object?>{
      'cycles': cycles,
      'elapsedMs': sw.elapsedMilliseconds,
      'avgMs': sw.elapsedMilliseconds / cycles,
    };
  }

  /// Provides a continuous diagnostics stream.
  Stream<Map<String, Object?>> diagnosticsStream({Duration interval = const Duration(seconds: 2)}) async* {
    while (true) {
      yield await snapshot();
      await Future.delayed(interval);
    }
  }

  /// Attempts a safe reconnect/recovery flow when a channel error occurs.
  Future<void> attemptRecovery({Duration retryDelay = const Duration(seconds: 1), int maxRetries = 3}) async {
    int attempt = 0;
    while (attempt < maxRetries) {
      try {
        await isEnabled();
        return; // success
      } catch (e) {
        attempt++;
        debugPrint('[WakelockPlusApi] recovery attempt \$attempt failed: \$e');
        await Future.delayed(retryDelay);
      }
    }
    throw PlatformException(code: 'recovery-failed', message: 'Failed to recover channel after \$maxRetries attempts.');
  }

  /// Synchronized set: ensures platform state matches [desired].
  Future<void> ensureState(bool desired) async {
    final IsEnabledMessage current = await isEnabled();
    if ((current.enabled ?? false) != desired) {
      await toggle(ToggleMessage(enable: desired));
    }
  }

  /// Convenience: logs a debug message.
  void log(String message) => debugPrint('[WakelockPlusApi] ' + message);
}
 
