name: pub_dev_publish_check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/lib/**'
      - '**/android/**'
      - '**/ios/**'
      - '**/pubspec.yaml'
      - '**/test/**'
      - '**/test_driver/**'
      - '**/assets/**'
      - '**/integration_test/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pub_dev_publish_check:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: "${{ matrix.package }} pub.dev publish check"
    strategy:
      matrix:
        package:
          - 'wakelock_plus'
          - 'wakelock_plus_platform_interface'
      fail-fast: false

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - name: "Install dependencies"
        run: flutter pub get --no-example
        working-directory: ${{ matrix.package }}
      - name: "Check pub.dev requirements"
        run: flutter pub publish --dry-run
        working-directory: ${{ matrix.package }}
